---
title: "List of Publications"
---

To make myself is one of the best researcher in county, I always do some research at small scale (for now!). Most of my reseach in related to GIS and Remote sensing in disaster. List of my publications is given below:

1.	**Khan, M. M.**, & Sarkar, S. K. (2019). LANDSLIDE MODELLING AND RISK ASSESSMENT: EVIDENCE FROM. *Journal of Engineering Science, 91-101.* <p/>
2.	**Khan, M. M.**, Prapti, S. T., Sarkar, S. K. A GIS BASED VULNERABILITY AND RISK ASSESSMENT OF FLOOD HAZARD IN COSTAL AREA: A CASE STUDY OF KOYRA UPAZILA, KHULNA. *International Conference on Disaster Risk Mitigation (ICDRM, 2017) Dhaka, Bangladesh: BUETJAPAN* <p/>
3.	**Khan, M. M.**, Sarkar, S. K. LANDSLIDES: AN INVENTORY ANALYSIS OF CHATTOGRAM CITY. *International Conference on Disaster Risk Mitigation (ICDRM, 2019) Dhaka, Bangladesh: BUETJAPAN*<p/>
4.	Zunayed, N., **Khan, M. M.**, (2017). A GIS BASED SUITABILITY ANALYSIS FOR WASTE DUMPING ZONE–TO IMPROVE THE PRESENT CONDITION OF THE COMMUNITY: A CASE STUDY ON WARD 24 (NIRALA), KHULNA CITY, BANGLADESH. *5th International Conference on solid waste management*. <p/>
5.	Prapti S. T.,**Khan, M. M.**, (2018) IMPACT OF PHYSICAL FEATURE ON TRAFFIC CONGESTION: A CASE STUDY OF KHULNA JESSOR HIGHWAY, KHULNA. *4th International Conference on Civil Engineering for Sustainable Development (ICCESD 2018), KUET, Khulna, Bangladesh*. <p/>
6.	**Khan, M.M.**, (2017). ANALYSIS OF CAUSES AND IMPACT OF WATER LOGGING IN KHULNA CITY OF BANGLADESH. *International Conference on Mechanical, Industrial and Materials Engineering 2017 (ICMIME2017) RUET, Rajshahi Bangladesh*. <p/>

